import {
  Bell, MessageSquare, Calendar, UtensilsCrossed, Wrench, Package,
  Building, BookOpen, Trophy, Shield, Briefcase, Cake, Award, Heart,
  Sparkles, DollarSign, Bookmark,
} from 'lucide-react';

export const MODULE_REGISTRY = [
  {
    id: 'announcements',
    label: 'News',
    description: 'College announcements and news',
    icon: Bell,
    href: '/dashboard/announcements',
    gradient: 'from-primary to-secondary',
  },
  {
    id: 'messages',
    label: 'Messages',
    description: 'Direct messaging with students and staff',
    icon: MessageSquare,
    href: '/dashboard/messages',
    gradient: 'from-primary to-secondary',
  },
  {
    id: 'events',
    label: 'Events',
    description: 'College calendar and upcoming events',
    icon: Calendar,
    href: '/dashboard/events',
    gradient: 'from-primary to-secondary',
  },
  {
    id: 'dining',
    label: 'Dining',
    description: 'Meal times and dining hall menus',
    icon: UtensilsCrossed,
    href: '/dashboard/dining',
    gradient: 'from-primary to-secondary',
  },
  {
    id: 'maintenance',
    label: 'Service',
    description: 'Log and track maintenance requests',
    icon: Wrench,
    href: '/dashboard/maintenance',
    gradient: 'from-muted-foreground to-secondary',
  },
  {
    id: 'parcels',
    label: 'Parcels',
    description: 'Parcel collection notifications',
    icon: Package,
    href: '/dashboard/parcels',
    gradient: 'from-primary to-secondary',
  },
  {
    id: 'floor',
    label: 'Floor',
    description: 'Floor community and common areas',
    icon: Building,
    href: '/dashboard/houses',
    gradient: 'from-warning to-secondary',
  },
  {
    id: 'academics',
    label: 'Academics',
    description: 'Academic support and resources',
    icon: BookOpen,
    href: '/dashboard/academics',
    gradient: 'from-primary to-secondary',
  },
  {
    id: 'cocurricular',
    label: 'Clubs',
    description: 'Co-curricular activities and clubs',
    icon: Trophy,
    href: '/dashboard/cocurricular',
    gradient: 'from-primary to-secondary',
  },
  {
    id: 'safe_disclosure',
    label: 'Make a Report',
    description: 'Confidential safe disclosure reporting',
    icon: Shield,
    href: '/dashboard/safe-disclosure',
    gradient: 'from-destructive to-orange-500',
  },
  {
    id: 'jobs',
    label: 'Jobs',
    description: 'Campus job opportunities',
    icon: Briefcase,
    href: '/dashboard/jobs',
    gradient: 'from-success to-success',
  },
  {
    id: 'birthdays',
    label: 'Birthdays',
    description: 'Upcoming resident birthdays',
    icon: Cake,
    href: '/dashboard/birthdays',
    gradient: 'from-primary to-secondary',
  },
  {
    id: 'recognition',
    label: 'Shoutouts',
    description: 'Give and receive peer recognition',
    icon: Award,
    href: '/dashboard/recognition',
    gradient: 'from-warning to-secondary',
  },
  {
    id: 'wellbeing',
    label: 'Wellbeing',
    description: 'Mental health and wellbeing resources',
    icon: Heart,
    href: '/dashboard/wellbeing',
    gradient: 'from-primary to-destructive',
  },
  {
    id: 'finance',
    label: 'Finance',
    description: 'Fees and financial information',
    icon: DollarSign,
    href: '/dashboard/finance',
    gradient: 'from-success to-secondary',
  },
  {
    id: 'bookings',
    label: 'Bookings',
    description: 'Room and facility bookings',
    icon: Bookmark,
    href: '/dashboard/bookings',
    gradient: 'from-primary to-secondary',
  },
];

export const AI_MODULE = {
  id: 'ai',
  label: 'AI Help',
  description: 'AI-powered campus assistant',
  icon: Sparkles,
  href: '/dashboard/ai',
  gradient: 'from-primary to-secondary',
};

export const getModuleById = (id) => MODULE_REGISTRY.find(m => m.id === id);

export const ALL_MODULE_IDS = MODULE_REGISTRY.map(m => m.id);
